name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node: [14, 16, 18]

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: node -v
      - uses: actions/cache@v3.2.6
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn test
